version: 2
updates:
  - package-ecosystem: npm
    directory: /templates/worker
    schedule:
      interval: weekly
    groups:
      worker-tooling:
        patterns: ["*"]
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
