// The deploy-button directory must be standalone: Cloudflare clones only it.
// Keep runtime, tests, dependency pins, and production bindings canonical here.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const source = join(root, "templates/worker");
const target = join(root, "templates/deploy-to-cloudflare");
const check = process.argv.includes("--check");
const files = new Map();
for (const folder of ["src", "test"]) {
  for (const name of readdirSync(join(source, folder))) {
    files.set(`${folder}/${name}`, readFileSync(join(source, folder, name), "utf8"));
  }
}
for (const name of ["package-lock.json", "vitest.config.ts"]) {
  files.set(name, readFileSync(join(source, name), "utf8"));
}
for (const name of ["docs/domain-setup.md", "scripts/check-subdomains.mjs"]) {
  files.set(name, readFileSync(join(source, name), "utf8"));
}
files.set("LICENSE.txt", readFileSync(join(root, "LICENSE.txt"), "utf8"));
const config = readFileSync(join(source, "wrangler.toml"), "utf8");
const productionStart = config.indexOf("[[env.production.r2_buckets]]");
if (productionStart < 0) throw new Error("Missing canonical production bindings");
files.set("wrangler.toml", [
  "# Generated by script/sync_deploy_template.mjs in cloudflare-email.",
  'name = "cloudflare-email-ingress"',
  'main = "src/index.js"',
  config.match(/^compatibility_date = .+$/m)[0],
  "", "[observability]", "enabled = true", "",
  config.slice(productionStart).replaceAll("env.production.", "").replaceAll("-production", ""),
].join("\n"));
const pkg = JSON.parse(readFileSync(join(source, "package.json"), "utf8"));
pkg.scripts = { ...pkg.scripts, deploy: "wrangler deploy", dev: "wrangler dev", check: "wrangler deploy --dry-run" };
pkg.cloudflare = { bindings: {
  RAILS_INGRESS_URL: { description: "Your deployed Rails HTTPS ingress URL, normally `https://your-app.com/rails/action_mailbox/cloudflare/inbound_emails`. Deploy cloudflare-email 0.3+ in Rails first." },
  INGRESS_SECRET: { description: "Paste the same random secret configured as `cloudflare.ingress_secret` in Rails credentials (or `CLOUDFLARE_INGRESS_SECRET`). Generate it with `openssl rand -hex 32`." },
  INBOUND_EMAIL_STORE: { description: "Private storage for pending email while Rails is unavailable. Use a new bucket for this app; never expire pending objects." },
  INBOUND_EMAIL_QUEUE: { description: "Delivery pointers for this app. The scheduled recovery pass also recovers retained mail after queue retries are exhausted." },
} };
files.set("package.json", `${JSON.stringify(pkg, null, 2)}\n`);
files.set(".dev.vars.example", "# Supply these in the Cloudflare deployment form. Never commit real values.\nRAILS_INGRESS_URL=\nINGRESS_SECRET=\n");
files.set(".gitignore", "node_modules/\n.wrangler/\n.dev.vars*\n!.dev.vars.example\n.env*\n!.env.example\n");
let stale = false;
for (const [name, content] of files) {
  const destination = join(target, name);
  if (check) {
    let actual;
    try { actual = readFileSync(destination, "utf8"); } catch { /* report missing */ }
    if (actual !== content) { console.error(`Stale deploy template: ${name}`); stale = true; }
  } else {
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, content);
  }
}
if (stale) {
  console.error("Run node script/sync_deploy_template.mjs and commit the generated files.");
  process.exit(1);
}
console.log(`${check ? "Verified" : "Synced"} ${files.size} deploy-template files.`);
